acme_store:
    resource: "@AcmeSuperStoreBundle/Controller/"
    type:     annotation
    prefix:   /

lawrence_crud:
    resource: "@LawrenceCrudBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
